window.TBE_ROUTES = [
  { slug: "nairobi-to-kampala", origin: "Nairobi", destination: "Kampala", country: "Uganda", flag: "🇺🇬", fare: 3500, duration: "12–14 hours", departure: "6:00 PM (Daily)", arrival: "7:00 AM next day", border: "Busia / Malaba OSBP", terminal: "River Road Terminal, Nairobi", stopovers: "Nakuru, Eldoret, Malaba, Jinja", bus: "Executive Luxury Coach" },
  { slug: "nairobi-to-kigali", origin: "Nairobi", destination: "Kigali", country: "Rwanda", flag: "🇷🇼", fare: 5500, duration: "18–20 hours", departure: "4:00 PM (Daily)", arrival: "11:00 AM next day", border: "Gatuna / Katuna OSBP", terminal: "River Road Terminal, Nairobi", stopovers: "Nakuru, Eldoret, Kampala, Gatuna", bus: "Executive Luxury Coach" },
  { slug: "nairobi-to-juba", origin: "Nairobi", destination: "Juba", country: "South Sudan", flag: "🇸🇸", fare: 7000, duration: "22–26 hours", departure: "2:00 PM (Mon, Wed, Sat)", arrival: "3:00 PM next day", border: "Nimule / Elegu Checkpoint", terminal: "Accra Road Terminal, Nairobi", stopovers: "Eldoret, Kampala, Gulu, Nimule", bus: "Cross-Border Express Coach" },
  { slug: "nairobi-to-goma", origin: "Nairobi", destination: "Goma", country: "DRC", flag: "🇨🇩", fare: 7500, duration: "24–28 hours", departure: "1:00 PM (Tue, Fri)", arrival: "5:00 PM next day", border: "Grande Barrière / Gisenyi", terminal: "Accra Road Terminal, Nairobi", stopovers: "Eldoret, Kampala, Kabale, Gisenyi", bus: "Cross-Border Express Coach" },
  { slug: "nairobi-to-bujumbura", origin: "Nairobi", destination: "Bujumbura", country: "Burundi", flag: "🇧🇮", fare: 7000, duration: "22–25 hours", departure: "3:00 PM (Wed, Sun)", arrival: "3:00 PM next day", border: "Kanyaru / Akanyaru Border", terminal: "River Road Terminal, Nairobi", stopovers: "Eldoret, Kampala, Kigali", bus: "Executive Luxury Coach" },
  { slug: "kampala-to-nairobi", origin: "Kampala", destination: "Nairobi", country: "Kenya", flag: "🇰🇪", fare: 3500, duration: "12–14 hours", departure: "6:00 PM (Daily)", arrival: "7:00 AM next day", border: "Malaba / Busia OSBP", terminal: "Bakuli Terminal, Sir Apollo Kaggwa Rd, Kampala", stopovers: "Jinja, Malaba, Eldoret, Nakuru", bus: "Executive Luxury Coach" },
  { slug: "kampala-to-kigali", origin: "Kampala", destination: "Kigali", country: "Rwanda", flag: "🇷🇼", fare: 2500, duration: "8–10 hours", departure: "8:00 PM (Daily)", arrival: "6:00 AM next day", border: "Gatuna OSBP", terminal: "Bakuli Terminal, Kampala", stopovers: "Masaka, Mbarara, Gatuna", bus: "Comfort Express Coach" },
  { slug: "kigali-to-nairobi", origin: "Kigali", destination: "Nairobi", country: "Kenya", flag: "🇰🇪", fare: 5500, duration: "18–20 hours", departure: "3:00 PM (Daily)", arrival: "10:00 AM next day", border: "Gatuna OSBP", terminal: "Nyabugogo Bus Park, Kigali", stopovers: "Gatuna, Kampala, Eldoret, Nakuru", bus: "Executive Luxury Coach" }
];

